TRANSLATIONS = {
    "en": {
        "discovery_hub": "Discovery Hub",
        "asset_primary": "Asset 1 (Primary)",
        "asset_optional": "Asset 2 (Optional)",
        "scenario_params": "Scenario Parameters",
        "sim_horizon": "Simulation Horizon (Days)",
        "path_count": "Path Count",
        "dca_settings": "DCA Settings",
        "dca_amount": "DCA Amount ($)",
        "frequency": "Frequency",
        "every_days": "Every {} days",
        "strategic_brief": "Strategic Brief",
        "awaiting_data": "Awaiting data...",
        "market_snapshot": "Market Snapshot",
        "intel_viz": "Intelligence Visualization",
        "price_action": "Price Action",
        "monte_carlo": "Monte Carlo Simulation",
        "scenario_sandbox": "Scenario Sandbox",
        "inst_intel": "Institutional Intel",
        "rel_perf": "Relative Performance",
        "volatility": "Volatility (Ann)",
        "ath_dist": "Distance from ATH",
        "sharpe": "Sharpe Ratio",
        "corr_matrix": "Correlation Matrix",
        "inst_alpha_feed": "Institutional Alpha Feed",
        "order_flow": "Order Flow Analysis",
        "whale_monitor": "Whale Activity Monitor",
        "sentiment_pulse": "Sentiment Pulse & News AI",
        "whale_detected": "Whale Transaction Detected",
        "vol_spike": "Volume spike confirmed",
        "no_anomalies": "No significant institutional anomalies in last 20 candles.",
        "disclaimer": "DISCLAIMER: FinanceSensei is an experimental AI decision-support interface. The strategic probabilities and insights generated are based on historical statistical models and should not be construed as financial, investment, or legal advice.",
        "sensei_sidebar_text": "Hey! I am monitoring the 10-year Treasury yields and Bitcoin liquidity clusters. Probabilities are shifting toward a breakout.",
        "ai_engine": "AI Engine",
        "ai_standard": "Standard Intelligence (Fast)",
        "ai_deep": "Deep Intelligence (Ollama)",
        "ai_model": "AI Model",
        "chat_tab": "Sensei Chat",
        "chat_placeholder": "Ask Sensei about market trends...",
        "chat_welcome": "I am Sensei. How can I assist your financial strategy today?",
        "nav_dashboard": "Terminal Dashboard",
        "nav_vision": "Project Vision & Market",
        "report_hub": "Strategic Report Hub",
        "generate_report": "Generate Weekly Alpha Report",
        "export_alpha": "Export Strategic Brief",
        "report_outlook": "Macro Outlook Synthesis",
        "vision_title": "The FinanceSensei Vision",
        "vision_mission": "Mission: Institutional Alpha for Everyone",
        "mission_text": "FinanceSensei was born to bridge the gap between retail investors and institutional desks. By combining high-frequency analytics with deterministic and generative AI, we provide situational awareness that was previously reserved for Bloomberg terminal users.",
        "market_strategy": "Market Strategy & Monetization",
        "strategy_text": "Our model follows an 'Open-Core' path. The analytical terminal remains open-source, while high-frequency data feeds, multi-chain alerting, and custom AI strategy models form the 'Pro' tier. Target markets include solo traders, crypto-native funds, and decentralized autonomous organizations (DAOs)."
    },
    "it": {
        "discovery_hub": "Hub di Scoperta",
        "asset_primary": "Asset 1 (Primario)",
        "asset_optional": "Asset 2 (Opzionale)",
        "scenario_params": "Parametri Scenario",
        "sim_horizon": "Orizzonte Simulazione (Giorni)",
        "path_count": "Conteggio Percorsi",
        "dca_settings": "Impostazioni DCA",
        "dca_amount": "Importo DCA ($)",
        "frequency": "Frequenza",
        "every_days": "Ogni {} giorni",
        "strategic_brief": "Brief Strategico",
        "awaiting_data": "In attesa di dati...",
        "market_snapshot": "Snapshot del Mercato",
        "intel_viz": "Visualizzazione Intelligence",
        "price_action": "Azione del Prezzo",
        "monte_carlo": "Simulazione Monte Carlo",
        "scenario_sandbox": "Sandbox dello Scenario",
        "inst_intel": "Intelligence Istituzionale",
        "rel_perf": "Performance Relativa",
        "volatility": "Volatilità (Ann)",
        "ath_dist": "Distanza da ATH",
        "sharpe": "Indice di Sharpe",
        "corr_matrix": "Matrice di Correlazione",
        "inst_alpha_feed": "Feed Alpha Istituzionale",
        "order_flow": "Analisi dell'Order Flow",
        "whale_monitor": "Monitoraggio Balene",
        "sentiment_pulse": "Sentiment e News AI",
        "whale_detected": "Transazione Balena Rilevata",
        "vol_spike": "Picco di volume confermato",
        "no_anomalies": "Nessuna anomalia istituzionale significativa nelle ultime 20 candele.",
        "disclaimer": "DISCLAIMER: FinanceSensei è un'interfaccia sperimentale di supporto alle decisioni AI. Le probabilità strategiche e gli insight generati si basano su modelli statistici storici e non devono essere interpretati come consigli finanziari, di investimento o legali.",
        "sensei_sidebar_text": "Hey! Sto monitorando i rendimenti dei Treasury a 10 anni e i cluster di liquidità di Bitcoin. Le probabilità si stanno spostando verso un breakout.",
        "ai_engine": "Motore AI",
        "ai_standard": "Intelligenza Standard (Rapida)",
        "ai_deep": "Intelligenza Profonda (Ollama)",
        "ai_model": "Modello AI",
        "chat_tab": "Sensei Chat",
        "chat_placeholder": "Chiedi al Sensei sui trend di mercato...",
        "chat_welcome": "Sono il Sensei. Come posso supportare la tua strategia finanziaria oggi?",
        "nav_dashboard": "Dashboard Terminale",
        "nav_vision": "Visione Progetto & Mercato",
        "report_hub": "Hub Report Strategici",
        "generate_report": "Genera Report Alpha Settimanale",
        "export_alpha": "Esporta Brief Strategico",
        "report_outlook": "Sintesi Outlook Macro",
        "vision_title": "La Visione di FinanceSensei",
        "vision_mission": "Missione: Alpha Istituzionale per Tutti",
        "mission_text": "FinanceSensei è nato per colmare il divario tra investitori retail e desk istituzionali. Combinando analisi ad alta frequenza con AI deterministica e generativa, offriamo una consapevolezza situazionale precedentemente riservata agli utenti di terminali Bloomberg.",
        "market_strategy": "Strategia di Mercato & Monetizzazione",
        "strategy_text": "Il nostro modello segue un percorso 'Open-Core'. Il terminale analitico rimane open-source, mentre i feed dati ad alta frequenza, gli alert multi-chain e i modelli di strategia AI personalizzati costituiscono il livello 'Pro'. I mercati target includono trader solisti, fondi crypto-native e organizzazioni autonome decentralizzate (DAO)."
    }
}

SENSEI_STRINGS = {
    "en": {
        "analyzing": "Analyzing {}. ",
        "rsi_overbought": "Relative Strength Index (RSI) is in overbought territory. Local cooling may be imminent. ",
        "rsi_oversold": "RSI indicates oversold conditions. Opportunity clusters forming. ",
        "vol_high": "Volatility is exceptionally high, indicating a speculative phase or cluster of institutional rebalancing. ",
        "vol_low": "Low volatility suggests a compression phase; expect a breakout as liquidity gathers. ",
        "ath_near": "The asset is testing historical resistance. Watch for a 'blue sky' breakout. ",
        "ath_far": "Deep discount relative to ATH. This is a high-convexity setup if macro tailwinds persist. ",
        "corr_coupling": "Note the strong coupling with {}. If {} softens, {} will likely face sell-side pressure.",
        "strat_prob": "\n\n💡 **STRATEGIC PROBABILITY:**\n",
        "prob_accumulation": "High-conviction build-up. The compression at low RSI suggests a 'Spring' phase is forming. Consider localized accumulation.",
        "prob_profit": "Over-extended delta. The statistical probability of a mean-reverting correction is >80%. Strategic profit taking or hedging is advised.",
        "prob_efficiency": "Exceptional efficiency. This asset remains an institutional favorite for risk-adjusted alpha.",
        "prob_neutral": "Neutral regime. Monitor macro benchmarks (S&P500/DXY) for the next directional impulse."
    },
    "it": {
        "analyzing": "Analisi di {}. ",
        "rsi_overbought": "L'indice di forza relativa (RSI) è in territorio di ipercomprato. Un raffreddamento locale potrebbe essere imminente. ",
        "rsi_oversold": "L'RSI indica condizioni di ipervenduto. Si stanno formando cluster di opportunità. ",
        "vol_high": "La volatilità è eccezionalmente alta, il che indica una fase speculativa o un cluster di riequilibrio istituzionale. ",
        "vol_low": "La bassa volatilità suggerisce una fase di compressione; aspettati un breakout man mano che la liquidità si accumula. ",
        "ath_near": "L'asset sta testando la resistenza storica. Attenzione a un breakout 'blue sky'. ",
        "ath_far": "Forte sconto rispetto all'ATH. Questa è una configurazione ad alta convessità se i venti macro favorevoli persistono. ",
        "corr_coupling": "Nota il forte accoppiamento con {}. Se {} si indebolisce, {} probabilmente subirà pressioni sul lato della vendita.",
        "strat_prob": "\n\n💡 **PROBABILITÀ STRATEGICA:**\n",
        "prob_accumulation": "Accumulo ad alta convinzione. La compressione a bassi livelli di RSI suggerisce che si sta formando una fase 'Spring'. Considera un accumulo localizzato.",
        "prob_profit": "Delta sovraesteso. La probabilità statistica di una correzione di ritorno alla media è >80%. Si consiglia una presa di profitto strategica o una copertura.",
        "prob_efficiency": "Efficienza eccezionale. Questo asset rimane uno dei preferiti dalle istituzioni per l'alpha aggiustato per il rischio.",
        "prob_neutral": "Regime neutrale. Monitora i benchmark macro (S&P500/DXY) per il prossimo impulso direzionale."
    }
}
